spring:
  application:
    name: QQBOT_SpringBoot

server:
  port: 33794
  servlet:
    encoding:
      force: true
      charset: utf-8
      enabled: true
  tomcat:
    uri-encoding: utf-8


botowner: "1668139313"

ep:
  url: "http://127.0.0.1:33793/"
  gmsg: "http://127.0.0.1:33793/send_group_msg"
  pmsg: "http://127.0.0.1:33793/send_private_msg"
  get_img: "http://127.0.0.1:33793/get_image"
  ocr: "http://127.0.0.1:33793/ocr_image"